services:
  db:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${MUSEUM_DB_NAME}
      BROKER_DB: ${BROKER_DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  api:
    build: .
    entrypoint: ["litestar", "run", "--app", "app:app"]
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - MUSEUM_DB_NAME=${MUSEUM_DB_NAME}
      - BROKER_DB_NAME=${BROKER_DB_NAME}
    depends_on:
      - db

  worker:
    build: .
    entrypoint: ["python", "worker_app.py"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - MUSEUM_DB_NAME=${MUSEUM_DB_NAME}
      - BROKER_DB_NAME=${BROKER_DB_NAME}
    depends_on:
      - db

  api-tester:
    build: ./api_tester
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
      - worker

volumes:
  postgres_data: