[project]
name = "museum-mgr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "onnx>=1.19.1",
    "peewee>=3.18.2",
    "ruff>=0.14.2",
]

[tool.poetry]
package-mode = false

